#pragma once

#include "videoconst.h"

constexpr int ROOMWIDTH_PIXELS{ 10 };
constexpr int ROOMHEIGHT_PIXELS{ 20 };
constexpr int ROOMPIXELSCOUNT{ ROOMWIDTH_PIXELS * ROOMHEIGHT_PIXELS };
constexpr int ROOMPIXELSIDE{ 46 };

constexpr int FLOOR{ 20 };

constexpr int ROOMWIDTH{ ROOMWIDTH_PIXELS * ROOMPIXELSIDE };
constexpr int ROOMHEIGHT{ ROOMHEIGHT_PIXELS * ROOMPIXELSIDE };

constexpr int ROOMLEFTSIDE_X{ SCREEN_MIDDLE_X - (ROOMWIDTH / 2) };
constexpr int ROOMLEFTSIDE_Y{ 50 };


constexpr int PLANE_MATRIXLENGTH{ 16 };
constexpr int CUBE_MATRIXLENGTH{ 4 };
constexpr int LGRIGHTLEFTT_MATRIXLENGTH{ 9 };
constexpr int REALTETRAMINO_LENGTH{ 4 };

constexpr int WALLPIXELARRAY_LENGTH{ ((ROOMHEIGHT_PIXELS + 1) * 2) + 
				(ROOMWIDTH_PIXELS) };

constexpr int LEFTWALL_LEFTX{ ROOMLEFTSIDE_X - ROOMPIXELSIDE };
constexpr int LEFTWALL_LEFTY{ ROOMLEFTSIDE_Y };
constexpr int DOWNWALL_LEFTX{ LEFTWALL_LEFTX + ROOMPIXELSIDE };
constexpr int DOWNWALL_LEFTY{ ROOMLEFTSIDE_Y + (ROOMHEIGHT_PIXELS * ROOMPIXELSIDE) };
constexpr int RIGHTWALL_LEFTX{ ROOMLEFTSIDE_X + (ROOMWIDTH_PIXELS * ROOMPIXELSIDE) };
constexpr int RIGHTWALL_LEFTY{ LEFTWALL_LEFTY };